name: Test and Build Image
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
    tags:
      - "v*"

env:
  REGISTRY: ghcr.io
  USERNAME: neutralboy
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Test with Maven
        run: mvn -B test --file pom.xml

  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - uses: actions/checkout@v4
      - name: Login to Github container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          platforms: ${{ env.PLATFORMS }}
          file: Dockerfile
          context: .
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max